insert into Customer (username, name) values ('alex', 'Алексей Макаров')
insert into Customer (username, name) values ('max', 'Максим Поташев')
insert into Customer (username, name) values ('nick', 'Николай Вороной')
insert into Customer (username, name) values ('mike', 'Михаил Боярский')
insert into Hotel (id, price, name, address, city, country) values (1, 4900, 'Холидей Инн Самара', 'Алексея Толстого 99', 'Самара', 'Россия')
insert into Hotel (id, price, name, address, city, country) values (2, 5610, 'Ost West Club', 'Садовая 210 A', 'Самара', 'Россия')
insert into Hotel (id, price, name, address, city, country) values (3, 4956, 'Ренессанс', 'Новосадовая ул.162 стр.В', 'Самара', 'Россия')
insert into Hotel (id, price, name, address, city, country) values (4, 4000, 'Хэмптон бай Хилтон', 'Льва Толстого 131', 'Самара', 'Россия')
insert into Hotel (id, price, name, address, city, country) values (5, 3000, 'Пирамида', '4-ый проезд 18', 'Самара', 'Россия')
insert into Hotel (id, price, name, address, city, country) values (6, 4900, 'Айсберг', 'Куйбышева 88', 'Самара', 'Россия')
insert into Hotel (id, price, name, address, city, country) values (7, 5100, 'Граф Орлов', 'Дачная 2', 'Самара', 'Россия')